name = "naderclass"
main = "index.js"
compatibility_date = "2026-08-01"

[[kv_namespaces]]
binding = "EXAM_KV"
id = "e6ebb01c9cd24a74918d684ac236b616"

[[durable_objects.bindings]]
name = "CLASSROOM"
class_name = "ClassRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ClassRoom"]
[ai]
binding = "AI"
